version: '3.1'

services:
  livejournal-telegrambot:
    build:
      context: .
    env_file:
      - ./.env/livejournal-telegrambot.env
#      - BOT_NAME=${BOT_NAME}
#      - BOT_TOKEN=${BOT_TOKEN}
    restart: always