version: '3.1'

services:
  telegrambot-db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: 'dev_telegrambot_db'
      MYSQL_USER: 'dev_telegrambot_db_user'
      MYSQL_PASSWORD: 'dev_telegrambot_db_password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3307:3306"
    expose:
      - '3307'
